# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'woven' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for woven

  target 'woven-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'wovenTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'woven-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for woven-tvOS


end
